name : Train
on:
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: self-hosted
    container:
      image: buraktag/mlops_case_study:latest
      options: --user root --ipc=host --gpus all
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Look train.py code
      run: cat train.py
    - name: Run train.py within Docker container
      run: python train.py
