name : Train
on:
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: self-hosted
    container:
      image: buraktag/mlops_case_study:latest
      options: --ipc=host --gpus all
    steps:
    - name: Run train.py within Docker container
      run: cd /workspace && python train.py
