name : Train
on:
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: self-hosted
    container:
      image: buraktag/mlops_case_study:latest
      options: --user root --ipc=host --gpus all
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Look around
      run: ls -l
    - name: Check where we are
      run: pwd

    - name: Run train.py within Docker container
      run: cd /workspace && python train.py
