name : Train
on:
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: self-hosted
    container:
      image: buraktag/mlops_case_study:latest
      options: --ipc=host --gpus all
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup DVC
      run: pip install dvc[gs]

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCLOUD }}'

    - name: Train within Docker container
      run: python train.py

    - name: Copy Best Model
      run: mkdir mymodels && cp mlops/IE-1001/weights/best.pt mymodels/best.pt

    - name: Send Best Model to DVC
      run: dvc add mymodels/best.pt

    - name: Git Add Model
      run: |
        git config --global --add safe.directory '*'
        git add mymodels/best.pt.dvc mymodels/.gitignore
        git commit -m "DVC best model added."

    - name: Push to DVC
      run: dvc push
