name : Train
on:
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: self-hosted
    container:
      image: buraktag/mlops_case_study:latest
      options: --ipc=host --gpus all
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Train within Docker container
      run: python train.py

    - name: Copy Best Model
      run: cp mlops/IE-1001/weights/best.pth mymodels/best.pth
