name: Train
on:
  pull_request:
    branches: [ main ]

jobs:
  train-model:
    runs-on: self-hosted
    container:
      image: buraktag/mlops_case_study:latest
      options: --ipc=host --gpus all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup DVC
        run: pip install dvc[gs]

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCLOUD }}'

      - name: Train within Docker container
        run: python train.py

      - name: Copy Best Model
        run: cp mlops/IE-1001/weights/best.pt mymodels/best.pt

      - name: Send Best Model to DVC
        run: dvc add mymodels/best.pt

      - name: Change Directory Status
        run: git config --global --add safe.directory '*'

      - name: Run Evaluate
        run: python val.py

      - name: Send Evaluation Results to DVC
        run: dvc add myresults/metrics.json

      - name: Check Differences
        run: dvc metrics diff --targets myresults/metrics.json >> results.md

      - uses: iterative/setup-cml@v1
      - name: Write Results
        run: |
          cml comment create report.md

      - name: Commit and Push Changes Evaluation to DVC
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update Model & Evaluation Results'
          file_pattern: myresults/metrics.json.dvc myresults/.gitignore mymodels/best.pt.dvc mymodels/.gitignore
          branch: ${{ github.head_ref }} # or specify your branch directly, e.g., 'main'

      - name: Push to DVC
        run: dvc push
