name : Run Tests
on : workflows-dispatch

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: echo "Github Action Done !"
